name: Run test build on PR
run-name: "Test build for PR #${{ github.event.pull_request.number }}"

on:
  pull_request:
    branches: [main]

env:
  BUILD_PATH: "."

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Install pnpm
          uses: pnpm/action-setup@v2
          with:
            version: latest
        - name: Setup Node.js Environment
          uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: pnpm
            cache-dependency-path: ${{ env.BUILD_PATH }}/pnpm-lock.yaml
        - name: Install dependencies
          run: pnpm install
        - name: Build site with Docusaurus
          run: pnpm build